version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"

  # Enable version updates for Python
  - package-ecosystem: "pip"
    directory: "/diagrams"
    schedule:
      interval: "weekly"
